apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: ghcr.io/banzaicloud/kafka-operator:latest
        name: manager
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          httpGet:
            port: 8081
            path: /healthz
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          httpGet:
            port: 8081
            path: /readyz
        ports:
        - containerPort: 9001
          name: alerts
          protocol: TCP
        - containerPort: 8081
          name: liveness-readiness-probes
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
