run:
    deadline: 2m

    skip-dirs:
        - client

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    # - dupl            # NOTE: intentionally disabled
    - errcheck
    - exhaustive
    - funlen
    # - gochecknoinits  # NOTE: intentionally disabled
    - goconst
    - gocritic # NOTE: remove nolinted functions
    - gocyclo
    - gofmt
    - goimports
#    - golint # NOTE: brokerID must be dealt as brokerId
#    - gomnd
    - goprintffuncname
#    - gosec # Note: Fixme when refactoring http calls
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
#    - noctx # Note: FIXME by adding refactoring http calls
    # - nolintlint      # NOTE: intentionally disabled
    - rowserrcheck
    - exportloopref
    - staticcheck
    - structcheck
#    - stylecheck # NOTE: brokerID must be dealt as brokerId
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 36
  dogsled:
    max-blank-identifiers: 3 # default: 2
  funlen:
    # FIXME: we need to refactor functions with length more then ~200 lines
    lines: 323        # default: 60
    statements: 100   # default: 40
  gocritic:
    disabled-checks:
      - commentFormatting
  golint:
    min-confidence: 0.1
  goimports:
    local-prefixes: github.com/banzaicloud
  lll:
    # FIXME: we should be able to reduce the length of lines to be closer to the default 120 lines
    line-length: 300  # default: 120
