topic:
  name: users
  partitions-num: 3
  replication-factor: 1
server:
  port: 9080
spring:
  kafka:
    bootstrap-servers:
      - ae5e4016cd51847fa8603c5478678d91-1161352389.us-east-1.elb.amazonaws.com:29092
    properties:
      schema.registry.url: http://a9ec9aafbe29c4406b884d1084d8e69b-575838169.us-east-1.elb.amazonaws.com:8081
      ssl.keystore.location: /var/tmp/keystore.jks
      ssl.keystore.password: "waGhDLvPTGnMNzHd"
      ssl.truststore.location: /var/tmp/truststore.jks
      ssl.truststore.password: "waGhDLvPTGnMNzHd"
      ssl.endpoint.identification.algorithm: ""
      security.protocol: SSL
    consumer:
      group-id: group_id
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info
