// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/banzaicloud/kafka-operator/pkg/apis/banzaicloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKafkaClusters implements KafkaClusterInterface
type FakeKafkaClusters struct {
	Fake *FakeBanzaicloudV1alpha1
	ns   string
}

var kafkaclustersResource = schema.GroupVersionResource{Group: "banzaicloud.banzaicloud.io", Version: "v1alpha1", Resource: "kafkaclusters"}

var kafkaclustersKind = schema.GroupVersionKind{Group: "banzaicloud.banzaicloud.io", Version: "v1alpha1", Kind: "KafkaCluster"}

// Get takes name of the kafkaCluster, and returns the corresponding kafkaCluster object, and an error if there is any.
func (c *FakeKafkaClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.KafkaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kafkaclustersResource, c.ns, name), &v1alpha1.KafkaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaCluster), err
}

// List takes label and field selectors, and returns the list of KafkaClusters that match those selectors.
func (c *FakeKafkaClusters) List(opts v1.ListOptions) (result *v1alpha1.KafkaClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kafkaclustersResource, kafkaclustersKind, c.ns, opts), &v1alpha1.KafkaClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KafkaClusterList{ListMeta: obj.(*v1alpha1.KafkaClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.KafkaClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kafkaClusters.
func (c *FakeKafkaClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kafkaclustersResource, c.ns, opts))

}

// Create takes the representation of a kafkaCluster and creates it.  Returns the server's representation of the kafkaCluster, and an error, if there is any.
func (c *FakeKafkaClusters) Create(kafkaCluster *v1alpha1.KafkaCluster) (result *v1alpha1.KafkaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kafkaclustersResource, c.ns, kafkaCluster), &v1alpha1.KafkaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaCluster), err
}

// Update takes the representation of a kafkaCluster and updates it. Returns the server's representation of the kafkaCluster, and an error, if there is any.
func (c *FakeKafkaClusters) Update(kafkaCluster *v1alpha1.KafkaCluster) (result *v1alpha1.KafkaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kafkaclustersResource, c.ns, kafkaCluster), &v1alpha1.KafkaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKafkaClusters) UpdateStatus(kafkaCluster *v1alpha1.KafkaCluster) (*v1alpha1.KafkaCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kafkaclustersResource, "status", c.ns, kafkaCluster), &v1alpha1.KafkaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaCluster), err
}

// Delete takes name of the kafkaCluster and deletes it. Returns an error if one occurs.
func (c *FakeKafkaClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kafkaclustersResource, c.ns, name), &v1alpha1.KafkaCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKafkaClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kafkaclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KafkaClusterList{})
	return err
}

// Patch applies the patch and returns the patched kafkaCluster.
func (c *FakeKafkaClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KafkaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kafkaclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.KafkaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaCluster), err
}
