name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: License cache
        uses: actions/cache@v3
        with:
          path: .licensei.cache
          key: license-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            license-v1-

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-cache

      - name: Vendor dependencies to retrieve licenses locally
        # Vendor deps before running https://github.com/goph/licensei
        # to avoid false-positive when modules github repo could not be determined
        run: go mod vendor

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

      - name: Build
        run: |
          make generate

      - name: Lint
        run: |
          make lint

      - name: Run tests
        run: |
          make test
