name: e2e-test

on:
  push:
    branches:
      - master
  pull_request:

env:
  IMG_E2E: koperator_e2e_test:${GITHUB_SHA}  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build docker image
        run: |
          GITHUB_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")
          #IMG=koperator_e2e_test:$GITHUB_SHA_SHORT make docker-build
          IMG=$IMG_E2E make docker-build

      - name: Setup Kind cluster
        id: setup-kind
        uses: ./.github/actions/kind-create

      - name: Load image into kind cluster
        run: |
          GITHUB_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")
          #IMG=koperator_e2e_test:$GITHUB_SHA_SHORT
          kind load docker-image $IMG_E2E --name e2e-kind


      - name: run tests
        env:
           KUBECONFIG: ${{ steps.setup-kind.outputs.kubeconfig }}
        run: |
          go work init
          go work use -r .
          #GITHUB_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")
          make test-e2e
