name: e2e-test

on:
  push:
    branches:
      - master
  pull_request:

env:
  REPOSITORY: koperator_e2e_test  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build docker image
        run: |
          IMG=$REPOSITORY:$GITHUB_SHA make docker-build

      - name: Setup Kind cluster
        id: setup-kind
        uses: ./.github/actions/kind-create

      - name: Load image into kind cluster
        run: |
          kind load docker-image $REPOSITORY:$GITHUB_SHA --name e2e-kind


      - name: Run E2E tests
        env:
           KUBECONFIG: ${{ steps.setup-kind.outputs.kubeconfig }}
        run: |
          go work init
          go work use -r .
          IMG_E2E=$REPOSITORY:$GITHUB_SHA make test-e2e
